### ISSUE TITLE
Add macos support?

### ISSUE THREAD

**Issue by Daenyth** [DazedNConfused-/CDDA-Game-Launcher#21]
I'd like to be able to use this on macos

It might be as easy as refreshing this PR from the base repo which was never merged: https://github.com/remyroy/CDDA-Game-Launcher/pull/112

**Comment by DazedNConfused-** [comment]
Howdy there! I am not against this idea at all. However, as a non-macOS user, it's currently impossible for me to implement, compile and/or verify the working condition of such binaries. At the very least this would require a developer with either access to or who uses a Mac as its main dev machine, that could both implement and test this potential version of the Launcher.

That being said, in my short time mantaining this fork of the Launcher, I have already seen lots of Windows-specific code that would need to either be refactored or removed outright. I currently don't know the feasibility of such endeavor without crippling core functionality of the Launcher (one of these things currently custom-tailored to Windows is being able to determine when the CDDA binary is running or not in order to, for example, make save backups).

**Comment by DazedNConfused-** [comment]
Given the above comments, it's currently impossible for me to implement a MacOS variant of the Launcher; at least not one with any sort of reliability that should be otherwise expected from properly-working/mature software.  

PRs are still absolutely welcome if someone actually manages to pull this off. In the meantime, I shall be closing this issue.

**Comment by DazedNConfused-** [comment]
Well, quite some time has passed since this issue first arrived. Remyroy's launcher may never achieve cross-platform support due to how tailored to Windows it is. _However_ I have gotten my hands on a Mac, and been working on a different launcher specifically tailored for macOS users:

https://github.com/DazedNConfused-/macata-launcher
