### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by TadhgEomonn** [DazedNConfused-/CDDA-Game-Launcher#46]
The new icon is underwhelming. (Preferred Remy's rocket, which was retained on the Win 10 desktop. )

I literally cannot tell what the new icon represents. It is too small, too dark (especially against a dark background), and to be discarded. Find something bigger, brighter, and better. Please.

**Comment by DazedNConfused-** [comment]
Howdy! The new icon was introduced as part of https://github.com/Fris0uman/CDDA-Game-Launcher/pull/8, which is another fork of the launcher I try to keep parity with - at least as long as the PRs don't collide with what I believe was Remy's vision for the Launcher project (thus why I have not merged, for example, other PRs like the one stripping functionality in order to make a "light" version of the Launcher). 

My guess would be it was a design choice driven by @Fris0uman's personal preferences more than anything, and given the rather innocuous nature of the change, I too decided to go along with it. 

I am absolutely not against changing the icon yet again into something else that could potentially give this fork it's own "identity". We can use this issue/ticket as a place where people can upload their personal picks and have a vote.

**Comment by TadhgEomonn** [comment]
What is the present icon?

**Comment by DazedNConfused-** [comment]
According to https://github.com/Fris0uman/CDDA-Game-Launcher/pull/8: 
> ![image](https://user-images.githubusercontent.com/41293484/162437799-450dc138-1e0c-48a8-a77a-e73c73b00024.png)
> Use the minninuke launcher made by Aunt Su [https://github.com/I-am-Erk/CDDA-Tilesets/blob/master/gfx/MShockXotto%2B/pngs_tiles_32x32/item/aunt_su_guns/mininuke_launcher.png](https://github.com/I-am-Erk/CDDA-Tilesets/blob/master/gfx/MShockXotto%2B/pngs_tiles_32x32/item/aunt_su_guns/mininuke_launcher.png?rgh-link-date=2022-04-08T12%3A44%3A12Z)

**Comment by DazedNConfused-** [comment]
That's fair. And since @hexagonrecursion introduced REUSE compliance into the project, proper licensing gained relevance and stopped being just an afterthought; so this makes the change all the more appropriate.

Nevertheless, if general consensus is that the new icon is hard to see/understand or otherwise feels like a downgrade to what we had before, I am in favor of changing it for whatever alternative makes the community the most content.

**Comment by DazedNConfused-** [comment]
This issue hasn't received further attention, so I am going to assume the new icon is sufficiently adequate (or perhaps _irrelevant_) for the majority of users.
