### ISSUE TITLE
Launcher.bat should use pythonw.exe for release builds

### ISSUE THREAD

**Issue by rodneyrod** [DazedNConfused-/CDDA-Game-Launcher#47]
Hi, not sure where the code is for this in the repo but the generated Launcher.bat in the install directory uses python.exe which also launches a persistent console window, useful for debugging, but if this used pythonw.exe instead it would look a bit more neat without the persistent console.

**Comment by DazedNConfused-** [comment]
Howdy!

Thank you for your input. This was a deliberate decision stemming from https://github.com/DazedNConfused-/CDDA-Game-Launcher/issues/9.

Basically, for reasons I cannot explain (Python is not my main platform, so I am sure there must be some under-the-hood intricacies at play that I am not familiar with), while using the windowless variant `pythonw.exe` the Launcher would crash without error nor stacktrace more or less in 1 out of 3 backup attempts. This was particularly aggravating to me because I am a notoriously save-scummy, thus I would experience these crashes in a near-constant fashion.

While toying around with Python configurations, I discovered that the console variant didn't crash as often. This coupled with an increased process priority made the crashes stop in their tracks overnight.

I realize that this was far from a perfect solution, but I had to weight the pros and cons. And at the end of the day, I considered that having properly working software triumphed the minor inconvenience of having a small Python console in the background.

**Comment by rodneyrod** [comment]
Thanks I wasn't aware of the issue, I'd be interested to see if I can help out somehow.
btw, does the behaviour sound similar to what this user is talking about, at the PyQt part?
https://stackoverflow.com/questions/45488531/python-cant-see-exception-that-is-getting-thrown/45488660#45488660

If it is I'll play around with doing the fix they mention.

**Comment by DazedNConfused-** [comment]
The issue linked seems related to a testing scenario. In here, whatever was happening that was making the Launcher crash was happening silently in runtime; more specifically there was a high chance for it to happen during the save backups and restorations. The crash outputted no logs/errors whatsoever, it just quit itself in the middle of the operation, leaving a corrupted save (or worse!), player world.

**Comment by rodneyrod** [comment]
nw if I get to the bottom of it I'll submit a pull
