### ISSUE TITLE
Startup python.exe error 0xc000007b

### ISSUE THREAD

**Issue by spamman63** [DazedNConfused-/CDDA-Game-Launcher#48]
When trying to start the launcher an error appears as follows
python.exe - Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application.
My guess at what's happening is that I'm running Windows 7 and the python version being used appears to be 3.9, which dropped support. Can anything be done about this to make the launcher Windows 7 compatible?

**Comment by DazedNConfused-** [comment]
Howdy!

That would be quite the trick. In theory one could always "just downgrade the Python version" and assume retro-compatibility. The deeper issue is: Win7 has fallen out of support, and I don't have a Win7 machine that could be used to test these hypothetical builds. That means I would not be able to fix any Win7-specific bugs (like this one) when they arise in the future. 

So I must regrettably say that, as long as I lack an adequate platform to test the software with in order to ensure its working condition with my own eyes, I cannot add support to Win7. I am sorry.
