### ISSUE TITLE
Hide Console Window By Default

### ISSUE THREAD

**Issue by ChromePoptart** [DazedNConfused-/CDDA-Game-Launcher#77]
### Is your feature request related to a problem? Please describe.

Following using the original remyroy launcher for a long time, I installed this version/fork of the launcher.  Upon opening it for the first time, I was slightly annoyed to see the console window open and then persist in the background after the launcher UI loads.

### Describe the solution you'd like

To maintain the behavior I'm used to from the original remyroy launcher (e.g., no background console window), I did some digging and found a simple solution.  In the root folder's "Launcher.bat" file, change
`start /realtime python.exe -m cddagl`
to
`start /realtime pythonw.exe -m cddagl`
Invoking the Python interpreter that contains the "w" hides the console window by default.

### Describe alternatives you've considered

If it's desired that the default behavior be for the console window to be shown, this request should be discarded.  However, coming over from the original remyroy launcher, it seems sensible to port over the default behavior from that project here.

**Comment by DazedNConfused-** [comment]
This is an unfortunate side effect of the fix for a very, _very_ jarring  and frequent crash bug that would leave save states corrupted, and that has been present going back to the original remyroy's launcher times: https://github.com/DazedNConfused-/CDDA-Game-Launcher/issues/9

In my ignorance of the codebase and/or Python in general (perhaps both), this was the only fix I could come up with. AFAIK the bug has been reported several times in the previous repo, and noone has been able to come up with a better fix as of yet. Having a small console window was deemed as a reasonable compromise in order to fix a data-breaking bug.

**Comment by ChromePoptart** [comment]
Ah, alright.  I'm glad to hear it was a conscious decision and not an oversight!  I myself have personally encountered an issue with the remyroy launcher a number of times in the past where it would abruptly stop and quit during the compression and creation of a save back-up -- not sure if that is the same as the issue you're referencing.  Positively, at least for me, I haven't encountered that crash for a long while (on the remyroy launcher nor ever with this one).  I'll try to remember and report back if I do encounter the crash now that I manually turned the console off for my launcher.

Would you like me to close this issue?
